/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sirshande.guiado;


import com.sirshande.guiado.Empleados;
import com.sirshande.TextPrompt;

/**
 *
 * @author Administrator
 */
public class EmpleadosFrm extends javax.swing.JFrame {
    //Declaracion de variables globales
    Empleados empleado; //Objeto empleado de la clase Empleados

    /**
     * Creates new form Empleados
     */
    public EmpleadosFrm() {
        initComponents();
        TextPrompt codigo = new TextPrompt("Ingrese su codigo", jtCodigo);
        TextPrompt nombre = new TextPrompt("Ingrese su nombre", jtNombre);
        TextPrompt sueldoBase = new TextPrompt("Ingrese su sueldo base", jtsueldoBase);
        TextPrompt horasExtras = new TextPrompt("Ingrese las horas extras", jthorasExtras);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtCodigo = new javax.swing.JTextField();
        jtCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtsueldoBase = new javax.swing.JTextField();
        jthorasExtras = new javax.swing.JTextField();
        jcbAreaLaboral = new javax.swing.JComboBox<>();
        jcbSeguro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaSalida = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, -1));

        jtCerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/closeOriginal.png"))); // NOI18N
        jtCerrar.setText("Cerrar");
        jtCerrar.setContentAreaFilled(false);
        jtCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtCerrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/closeOriginal.png"))); // NOI18N
        jtCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/closeCopy.png"))); // NOI18N
        jtCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jtCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 6, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Uso de Clases, Objetos, atributos  y Métodos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, -1));
        jPanel1.add(jtsueldoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, -1));
        jPanel1.add(jthorasExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, -1));

        jcbAreaLaboral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "SISTEMAS", "ADMINISTRACION", "MARKETING" }));
        jPanel1.add(jcbAreaLaboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jcbSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONAR", "AFP", "SNP" }));
        jPanel1.add(jcbSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, -1));

        jtaSalida.setColumns(20);
        jtaSalida.setRows(5);
        jScrollPane1.setViewportView(jtaSalida);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 430, 220));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/createOriginal.png"))); // NOI18N
        jButton1.setText("Crear Objeto");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/createOriginal.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/createCopy.png"))); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 100, 110));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/viewOriginal.png"))); // NOI18N
        jButton2.setText("Mostrar Info del Objeto");
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/viewOriginal.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/viewCopy.png"))); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/clearOriginal.png"))); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.setContentAreaFilled(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/clearOriginal.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/clearCopy.png"))); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jtCerrarActionPerformed
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        //Capturando la informacion de los empleados de los objetos del formulario
        String cod=jtCodigo.getText();
        String nom=jtNombre.getText();
        String seguro=jcbSeguro.getSelectedItem().toString();
        double sueldo=Double.parseDouble(jtsueldoBase.getText());
        double h_extras=Double.parseDouble(jthorasExtras.getText());
        String area=jcbAreaLaboral.getSelectedItem().toString();
        //Creando el objeto empleado de la clase Empleados
        empleado= new Empleados(cod,area,area,sueldo,h_extras,seguro);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        //Extrayendo la informacion de los atributos y metodos de la clase
        jtaSalida.append("Objeto Número     : "+ Empleados.getContador()+"\n");
        jtaSalida.append("Codigo            : "+ empleado.codigo+"\n");
        jtaSalida.append("Nombre            : "+ empleado.nombre.toUpperCase()+"\n");
        jtaSalida.append("Seguro            : "+ empleado.tipo_seg+"\n");
        jtaSalida.append("Sueldo base       : "+ empleado.sueldoBase+"\n");
        jtaSalida.append("Horas Extras      : "+ empleado.horasExtras+"\n");
        jtaSalida.append("Area              : "+ empleado.area.toUpperCase()+"\n");
        jtaSalida.append("Monto Extra       : "+ empleado.montoHExtras()+"\n");
        jtaSalida.append("Monto Seguro      : "+ empleado.montoSeguro()+"\n");
        jtaSalida.append("Monto Essalud     : "+ empleado.montoEssalud()+"\n");
        jtaSalida.append("Monto de Descuentos       : "+ empleado.montoDescuentos()+"\n");
        jtaSalida.append("Sueldo bruto      : "+ empleado.sueldoBruto()+"\n");
        jtaSalida.append("Sueldo Neto       : "+ empleado.sueldoNeto()+"\n");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Limpiando los objetos
        jtCodigo.setText("");
        jtNombre.setText("");
        jcbSeguro.setSelectedItem(0);
        jtsueldoBase.setText("");
        jthorasExtras.setText("");
        jcbAreaLaboral.setSelectedItem(0);
        jtCodigo.requestFocus();
        jtaSalida.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadosFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbAreaLaboral;
    private javax.swing.JComboBox<String> jcbSeguro;
    private javax.swing.JButton jtCerrar;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextArea jtaSalida;
    private javax.swing.JTextField jthorasExtras;
    private javax.swing.JTextField jtsueldoBase;
    // End of variables declaration//GEN-END:variables
}
