/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.sirshande;

/**
 *
 * @author Administrator
 */
public class EmpleadosFrm extends javax.swing.JFrame {
    //Atributos
    String codigo;
    String nombre;
    String area;
    double sueldoBase;
    double horasExtras;
    String tipo_seg;
    //Valores comunes a todos  los objetos
    private static double porc_Afp=0.11;
    private static double porc_Snp=0.06;
    private static double porc_Essalud=0.03;
    private static int contador=0;
    //Constructor

    public EmpleadosFrm(String codigo, String nombre, String area, double sueldoBase, double horasExtras, String tipo_seg) {
        contador++; //contando la cantidad de empleados generados con la clase
        //actualizando la informacion de los atributos de la clase
        this.codigo = codigo;
        this.nombre = nombre;
        this.area = area;
        this.sueldoBase = sueldoBase;
        this.horasExtras = horasExtras;
        this.tipo_seg = tipo_seg;
    }
    //********************METODO ADICIONAL**********************
    //Calculando el monto  extra
    public double montoExtra(){
        return sueldoBase * horasExtras  / 240;
    }
    //Calculando el monto de seguro
    public double montoSeguro(){
        if(tipo_seg.equalsIgnoreCase("AFP 💼"))
            return sueldoBase * porc_Afp;
        if(tipo_seg.equalsIgnoreCase("SNP 🏦"))
            return sueldoBase * porc_Snp;
        return 0;
    }
    //Calculando el sueldo Neto

    /**
     * Creates new form Empleados
     */
    public EmpleadosFrm() {
        initComponents();
        TextPrompt codigo = new TextPrompt("Ingrese su codigo", jtCodigo);
        TextPrompt nombre = new TextPrompt("Ingrese su nombre", jtNombre);
        TextPrompt sueldoBase = new TextPrompt("Ingrese su sueldo base", jtsueldoBase);
        TextPrompt horasExtras = new TextPrompt("Ingrese las horas extras", jthorasExtras);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtCodigo = new javax.swing.JTextField();
        jtCerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtsueldoBase = new javax.swing.JTextField();
        jthorasExtras = new javax.swing.JTextField();
        jcbAreaLaboral = new javax.swing.JComboBox<>();
        jcbSeguro = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaSalida = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 255));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 150, -1));

        jtCerrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/closeOriginal.png"))); // NOI18N
        jtCerrar.setText("Cerrar");
        jtCerrar.setContentAreaFilled(false);
        jtCerrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jtCerrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/closeOriginal.png"))); // NOI18N
        jtCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/closeCopy.png"))); // NOI18N
        jtCerrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(jtCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(363, 6, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Uso de Clases, Objetos, atributos  y Métodos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel1.add(jtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, -1));
        jPanel1.add(jtsueldoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 150, -1));
        jPanel1.add(jthorasExtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, -1));

        jcbAreaLaboral.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ÁREA  🏢", "SISTEMAS 💻", "ADMINISTRACIÓN 📊", "MARKETING  📈" }));
        jPanel1.add(jcbAreaLaboral, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, -1));

        jcbSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO DE SEGURO 🏥", "SNP 🏦", "AFP 💼" }));
        jPanel1.add(jcbSeguro, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 150, -1));

        jtaSalida.setColumns(20);
        jtaSalida.setRows(5);
        jScrollPane1.setViewportView(jtaSalida);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 430, 220));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/createOriginal.png"))); // NOI18N
        jButton1.setText("Crear Objeto");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/createOriginal.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/createCopy.png"))); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 100, 110));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/viewOriginal.png"))); // NOI18N
        jButton2.setText("Mostrar Info del Objeto");
        jButton2.setContentAreaFilled(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/viewOriginal.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/viewCopy.png"))); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, -1, -1));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/clearOriginal.png"))); // NOI18N
        jButton3.setText("Limpiar");
        jButton3.setContentAreaFilled(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/clearOriginal.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sirshande/imagenes/clearCopy.png"))); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jtCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpleadosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpleadosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpleadosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpleadosFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpleadosFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbAreaLaboral;
    private javax.swing.JComboBox<String> jcbSeguro;
    private javax.swing.JButton jtCerrar;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextArea jtaSalida;
    private javax.swing.JTextField jthorasExtras;
    private javax.swing.JTextField jtsueldoBase;
    // End of variables declaration//GEN-END:variables
}
